/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts_.$alertId'
import { Route as BusesBusIdRouteImport } from './routes/buses.$busId'
import { Route as DirectionsJourneyIdRouteImport } from './routes/directions.$journeyId'
import { Route as LiveDirectionsJourneyIdRouteImport } from './routes/live-directions.$journeyId'
import { Route as OnboardingLandingRouteImport } from './routes/onboarding.landing'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding.language'
import { Route as OnboardingLocationRouteImport } from './routes/onboarding.location'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as StopsIdRouteImport } from './routes/stops.$id'
import { Route as StopsIdIndexRouteImport } from './routes/stops.$id.index'
import { Route as StopsIdTrackArrivalIdRouteImport } from './routes/stops.$id.track.$arrivalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/alerts_/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusesBusIdRoute = BusesBusIdRouteImport.update({
  id: '/buses/$busId',
  path: '/buses/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsJourneyIdRoute = DirectionsJourneyIdRouteImport.update({
  id: '/directions/$journeyId',
  path: '/directions/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDirectionsJourneyIdRoute = LiveDirectionsJourneyIdRouteImport.update({
  id: '/live-directions/$journeyId',
  path: '/live-directions/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLandingRoute = OnboardingLandingRouteImport.update({
  id: '/onboarding/landing',
  path: '/onboarding/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/onboarding/language',
  path: '/onboarding/language',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLocationRoute = OnboardingLocationRouteImport.update({
  id: '/onboarding/location',
  path: '/onboarding/location',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsIdRoute = StopsIdRouteImport.update({
  id: '/stops/$id',
  path: '/stops/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsIdIndexRoute = StopsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StopsIdRoute,
} as any)
const StopsIdTrackArrivalIdRoute = StopsIdTrackArrivalIdRouteImport.update({
  id: '/track/$arrivalId',
  path: '/track/$arrivalId',
  getParentRoute: () => StopsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/buses/$busId': typeof BusesBusIdRoute
  '/directions/$journeyId': typeof DirectionsJourneyIdRoute
  '/live-directions/$journeyId': typeof LiveDirectionsJourneyIdRoute
  '/onboarding/landing': typeof OnboardingLandingRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/stops/$id': typeof StopsIdRouteWithChildren
  '/stops/$id/': typeof StopsIdIndexRoute
  '/stops/$id/track/$arrivalId': typeof StopsIdTrackArrivalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/buses/$busId': typeof BusesBusIdRoute
  '/directions/$journeyId': typeof DirectionsJourneyIdRoute
  '/live-directions/$journeyId': typeof LiveDirectionsJourneyIdRoute
  '/onboarding/landing': typeof OnboardingLandingRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/stops/$id': typeof StopsIdIndexRoute
  '/stops/$id/track/$arrivalId': typeof StopsIdTrackArrivalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/plan': typeof PlanRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/alerts_/$alertId': typeof AlertsAlertIdRoute
  '/buses/$busId': typeof BusesBusIdRoute
  '/directions/$journeyId': typeof DirectionsJourneyIdRoute
  '/live-directions/$journeyId': typeof LiveDirectionsJourneyIdRoute
  '/onboarding/landing': typeof OnboardingLandingRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/location': typeof OnboardingLocationRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/stops/$id': typeof StopsIdRouteWithChildren
  '/stops/$id/': typeof StopsIdIndexRoute
  '/stops/$id/track/$arrivalId': typeof StopsIdTrackArrivalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/home'
    | '/plan'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/alerts/$alertId'
    | '/buses/$busId'
    | '/directions/$journeyId'
    | '/live-directions/$journeyId'
    | '/onboarding/landing'
    | '/onboarding/language'
    | '/onboarding/location'
    | '/routes/$routeId'
    | '/stops/$id'
    | '/stops/$id/'
    | '/stops/$id/track/$arrivalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/home'
    | '/plan'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/alerts/$alertId'
    | '/buses/$busId'
    | '/directions/$journeyId'
    | '/live-directions/$journeyId'
    | '/onboarding/landing'
    | '/onboarding/language'
    | '/onboarding/location'
    | '/routes/$routeId'
    | '/stops/$id'
    | '/stops/$id/track/$arrivalId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/favorites'
    | '/home'
    | '/plan'
    | '/schedule'
    | '/search'
    | '/settings'
    | '/alerts_/$alertId'
    | '/buses/$busId'
    | '/directions/$journeyId'
    | '/live-directions/$journeyId'
    | '/onboarding/landing'
    | '/onboarding/language'
    | '/onboarding/location'
    | '/routes/$routeId'
    | '/stops/$id'
    | '/stops/$id/'
    | '/stops/$id/track/$arrivalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  PlanRoute: typeof PlanRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
  BusesBusIdRoute: typeof BusesBusIdRoute
  DirectionsJourneyIdRoute: typeof DirectionsJourneyIdRoute
  LiveDirectionsJourneyIdRoute: typeof LiveDirectionsJourneyIdRoute
  OnboardingLandingRoute: typeof OnboardingLandingRoute
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingLocationRoute: typeof OnboardingLocationRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  StopsIdRoute: typeof StopsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts_/$alertId': {
      id: '/alerts_/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buses/$busId': {
      id: '/buses/$busId'
      path: '/buses/$busId'
      fullPath: '/buses/$busId'
      preLoaderRoute: typeof BusesBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions/$journeyId': {
      id: '/directions/$journeyId'
      path: '/directions/$journeyId'
      fullPath: '/directions/$journeyId'
      preLoaderRoute: typeof DirectionsJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-directions/$journeyId': {
      id: '/live-directions/$journeyId'
      path: '/live-directions/$journeyId'
      fullPath: '/live-directions/$journeyId'
      preLoaderRoute: typeof LiveDirectionsJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/landing': {
      id: '/onboarding/landing'
      path: '/onboarding/landing'
      fullPath: '/onboarding/landing'
      preLoaderRoute: typeof OnboardingLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/onboarding/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/location': {
      id: '/onboarding/location'
      path: '/onboarding/location'
      fullPath: '/onboarding/location'
      preLoaderRoute: typeof OnboardingLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/$id': {
      id: '/stops/$id'
      path: '/stops/$id'
      fullPath: '/stops/$id'
      preLoaderRoute: typeof StopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/$id/': {
      id: '/stops/$id/'
      path: '/'
      fullPath: '/stops/$id/'
      preLoaderRoute: typeof StopsIdIndexRouteImport
      parentRoute: typeof StopsIdRoute
    }
    '/stops/$id/track/$arrivalId': {
      id: '/stops/$id/track/$arrivalId'
      path: '/track/$arrivalId'
      fullPath: '/stops/$id/track/$arrivalId'
      preLoaderRoute: typeof StopsIdTrackArrivalIdRouteImport
      parentRoute: typeof StopsIdRoute
    }
  }
}

interface StopsIdRouteChildren {
  StopsIdIndexRoute: typeof StopsIdIndexRoute
  StopsIdTrackArrivalIdRoute: typeof StopsIdTrackArrivalIdRoute
}

const StopsIdRouteChildren: StopsIdRouteChildren = {
  StopsIdIndexRoute: StopsIdIndexRoute,
  StopsIdTrackArrivalIdRoute: StopsIdTrackArrivalIdRoute,
}

const StopsIdRouteWithChildren =
  StopsIdRoute._addFileChildren(StopsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  PlanRoute: PlanRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AlertsAlertIdRoute: AlertsAlertIdRoute,
  BusesBusIdRoute: BusesBusIdRoute,
  DirectionsJourneyIdRoute: DirectionsJourneyIdRoute,
  LiveDirectionsJourneyIdRoute: LiveDirectionsJourneyIdRoute,
  OnboardingLandingRoute: OnboardingLandingRoute,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingLocationRoute: OnboardingLocationRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  StopsIdRoute: StopsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
